# Generated by Django 4.2.6 on 2023-11-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_delete_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='barcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
            ],
        ),
    ]
