# Generated by Django 4.2.6 on 2023-11-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                
                ('barcode', models.CharField(max_length=50)),
               
            ],
        ),
    ]
