# Generated by Django 4.2.6 on 2023-11-03 10:35

from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('log_in', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='data',
            
        ),
    ]
